# Data Acquisition

CS 418 football project. Loads all four of our datasets into dataframes.

**Research questions:**
- Is rushing or passing more effective in winning NFL games?
- Do the stats suggest punting or going for it on 4th down?
- How much does average WR separation correlate with receiving yardage?

All four datasets come from [nflverse](https://github.com/nflverse/nflreadpy),
accessed through the `nflreadpy` package (one shared import below instead of
repeating it per dataset).

In [1]:
import polars as pl
import nflreadpy as nfl

## Primary dataset 1: Play-by-play (`playbyplay`)

One row = one play from a 2025 game. Notable columns: `posteam`, `yards_gained`,
`success`, `passer`, `rusher`, `receiver`.

In [2]:
playbyplay = nfl.load_pbp(2025)
playbyplay.shape

(48771, 372)

In [3]:
playbyplay.describe()

shape: (9, 373)
┌─────┬─────┬─────┬─────┬───┬────────┬───────┬───────┬───────┐
│ sta ┆ pla ┆ gam ┆ old ┆ … ┆ xyac_s ┆ xyac_ ┆ xpass ┆ pass_ │
│ tis ┆ y_i ┆ e_i ┆ _ga ┆   ┆ uccess ┆ fd    ┆ ---   ┆ oe    │
│ tic ┆ d   ┆ d   ┆ me_ ┆   ┆ ---    ┆ ---   ┆ f64   ┆ ---   │
│ --- ┆ --- ┆ --- ┆ id  ┆   ┆ f64    ┆ f64   ┆       ┆ f64   │
│ str ┆ f64 ┆ str ┆ --- ┆   ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆ str ┆   ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═══╪════════╪═══════╪═══════╪═══════╡
│ cou ┆ 487 ┆ 487 ┆ 487 ┆ … ┆ 16324. ┆ 16324 ┆ 37064 ┆ 36019 │
│ nt  ┆ 71. ┆ 71  ┆ 71  ┆   ┆ 0      ┆ .0    ┆ .0    ┆ .0    │
│     ┆ 0   ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ nul ┆ 0.0 ┆ 0   ┆ 0   ┆ … ┆ 32447. ┆ 32447 ┆ 11707 ┆ 12752 │
│ l_c ┆     ┆     ┆     ┆   ┆ 0      ┆ .0    ┆ .0    ┆ .0    │
│ oun ┆     ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ t   ┆     ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ mea ┆ 218 ┆ nul ┆ nul ┆ … ┆ 0.7796 ┆ 0.584 ┆ 0.627 ┆ -1.61 │
│ n   ┆ 2.1 ┆ l   ┆ l   ┆   ┆ 57     ┆ 833   ┆ 277   ┆ 0125  │
│     ┆ 063 ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│     ┆ 54  ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ std ┆ 127 ┆ nul ┆ nul ┆ … ┆ 0.2533 ┆ 0.357 ┆ 0.242 ┆ 42.53 │
│     ┆ 3.7 ┆ l   ┆ l   ┆   ┆ 32     ┆ 027   ┆ 531   ┆ 9063  │
│     ┆ 463 ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│     ┆ 93  ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ min ┆ 1.0 ┆ 202 ┆ 202 ┆ … ┆ 0.0389 ┆ 0.010 ┆ 0.013 ┆ -99.5 │
│     ┆     ┆ 5_0 ┆ 509 ┆   ┆        ┆ 31    ┆ 008   ┆ 38189 │
│     ┆     ┆ 1_A ┆ 040 ┆   ┆        ┆       ┆       ┆       │
│     ┆     ┆ RI_ ┆ 0   ┆   ┆        ┆       ┆       ┆       │
│     ┆     ┆ NO  ┆     ┆   ┆        ┆       ┆       ┆       │
│ 25% ┆ 108 ┆ nul ┆ nul ┆ … ┆ 0.5606 ┆ 0.243 ┆ 0.454 ┆ -42.7 │
│     ┆ 8.0 ┆ l   ┆ l   ┆   ┆ 3      ┆ 865   ┆ 001   ┆ 02234 │
│ 50% ┆ 216 ┆ nul ┆ nul ┆ … ┆ 0.9839 ┆ 0.480 ┆ 0.599 ┆ 3.681 │
│     ┆ 0.0 ┆ l   ┆ l   ┆   ┆ 07     ┆ 26    ┆ 471   ┆ 308   │
│ 75% ┆ 325 ┆ nul ┆ nul ┆ … ┆ 1.0    ┆ 0.999 ┆ 0.860 ┆ 32.96 │
│     ┆ 6.0 ┆ l   ┆ l   ┆   ┆        ┆ 362   ┆ 091   ┆ 1887  │
│ max ┆ 551 ┆ 202 ┆ 202 ┆ … ┆ 1.0    ┆ 1.0   ┆ 0.996 ┆ 97.84 │
│     ┆ 9.0 ┆ 5_2 ┆ 602 ┆   ┆        ┆       ┆ 563   ┆ 8164  │
│     ┆     ┆ 2_S ┆ 080 ┆   ┆        ┆       ┆       ┆       │
│     ┆     ┆ EA_ ┆ 0   ┆   ┆        ┆       ┆       ┆       │
│     ┆     ┆ NE  ┆     ┆   ┆        ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴───┴────────┴───────┴───────┴───────┘

## Primary dataset 2: Player weekly stats (`player_stats`)

One row = one player's stat line for one week of one season (2021-2025).
Includes `rushing_*` and `passing_*` columns side by side -- the main dataset
for comparing rushing vs. passing production at the player level.

In [4]:
player_stats = nfl.load_player_stats([2021, 2022, 2023, 2024, 2025])
player_stats.shape

(94848, 150)

In [5]:
player_stats.head()

shape: (5, 150)
┌─────┬─────┬─────┬─────┬───┬────────┬───────┬───────┬───────┐
│ pla ┆ pla ┆ pla ┆ pos ┆ … ┆ pt_ret ┆ pt_ne ┆ fanta ┆ fanta │
│ yer ┆ yer ┆ yer ┆ iti ┆   ┆ urn_td ┆ t_yar ┆ sy_po ┆ sy_po │
│ _id ┆ _na ┆ _di ┆ on  ┆   ┆ s      ┆ ds    ┆ ints  ┆ ints_ │
│ --- ┆ me  ┆ spl ┆ --- ┆   ┆ ---    ┆ ---   ┆ ---   ┆ ppr   │
│ str ┆ --- ┆ ay_ ┆ str ┆   ┆ i32    ┆ i32   ┆ f64   ┆ ---   │
│     ┆ str ┆ nam ┆     ┆   ┆        ┆       ┆       ┆ f64   │
│     ┆     ┆ e   ┆     ┆   ┆        ┆       ┆       ┆       │
│     ┆     ┆ --- ┆     ┆   ┆        ┆       ┆       ┆       │
│     ┆     ┆ str ┆     ┆   ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═══╪════════╪═══════╪═══════╪═══════╡
│ 00- ┆ T.B ┆ Tom ┆ QB  ┆ … ┆ 0      ┆ 0     ┆ 27.16 ┆ 27.16 │
│ 001 ┆ rad ┆ Bra ┆     ┆   ┆        ┆       ┆       ┆       │
│ 959 ┆ y   ┆ dy  ┆     ┆   ┆        ┆       ┆       ┆       │
│ 6   ┆     ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ 00- ┆ A.L ┆ And ┆ P   ┆ … ┆ 0      ┆ 124   ┆ 0.0   ┆ 0.0   │
│ 002 ┆ ee  ┆ y   ┆     ┆   ┆        ┆       ┆       ┆       │
│ 282 ┆     ┆ Lee ┆     ┆   ┆        ┆       ┆       ┆       │
│ 4   ┆     ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ 00- ┆ B.R ┆ Ben ┆ QB  ┆ … ┆ 0      ┆ 0     ┆ 12.02 ┆ 12.02 │
│ 002 ┆ oet ┆ Roe ┆     ┆   ┆        ┆       ┆       ┆       │
│ 292 ┆ hli ┆ thl ┆     ┆   ┆        ┆       ┆       ┆       │
│ 4   ┆ sbe ┆ isb ┆     ┆   ┆        ┆       ┆       ┆       │
│     ┆ rge ┆ erg ┆     ┆   ┆        ┆       ┆       ┆       │
│     ┆ r   ┆ er  ┆     ┆   ┆        ┆       ┆       ┆       │
│ 00- ┆ R.G ┆ Rob ┆ K   ┆ … ┆ 0      ┆ 0     ┆ 0.0   ┆ 0.0   │
│ 002 ┆ oul ┆ bie ┆     ┆   ┆        ┆       ┆       ┆       │
│ 325 ┆ d   ┆ Gou ┆     ┆   ┆        ┆       ┆       ┆       │
│ 2   ┆     ┆ ld  ┆     ┆   ┆        ┆       ┆       ┆       │
│ 00- ┆ Aa. ┆ Aar ┆ QB  ┆ … ┆ 0      ┆ 0     ┆ 1.32  ┆ 1.32  │
│ 002 ┆ Rod ┆ on  ┆     ┆   ┆        ┆       ┆       ┆       │
│ 345 ┆ ger ┆ Rod ┆     ┆   ┆        ┆       ┆       ┆       │
│ 9   ┆ s   ┆ ger ┆     ┆   ┆        ┆       ┆       ┆       │
│     ┆     ┆ s   ┆     ┆   ┆        ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴───┴────────┴───────┴───────┴───────┘

In [6]:
# Columns relevant to rushing vs. passing
cols = [c for c in player_stats.columns if c.startswith('rushing_') or c.startswith('passing_')]
cols

['passing_yards',
 'passing_tds',
 'passing_interceptions',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_cpoe',
 'passing_2pt_conversions',
 'passing_10',
 'passing_16',
 'passing_20',
 'passing_40',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'rushing_10',
 'rushing_12',
 'rushing_20',
 'rushing_40']

In [7]:
player_stats.select(cols).describe()

shape: (9, 25)
┌─────┬─────┬─────┬─────┬───┬────────┬───────┬───────┬───────┐
│ sta ┆ pas ┆ pas ┆ pas ┆ … ┆ rushin ┆ rushi ┆ rushi ┆ rushi │
│ tis ┆ sin ┆ sin ┆ sin ┆   ┆ g_10   ┆ ng_12 ┆ ng_20 ┆ ng_40 │
│ tic ┆ g_y ┆ g_t ┆ g_i ┆   ┆ ---    ┆ ---   ┆ ---   ┆ ---   │
│ --- ┆ ard ┆ ds  ┆ nte ┆   ┆ f64    ┆ f64   ┆ f64   ┆ f64   │
│ str ┆ s   ┆ --- ┆ rce ┆   ┆        ┆       ┆       ┆       │
│     ┆ --- ┆ f64 ┆ pti ┆   ┆        ┆       ┆       ┆       │
│     ┆ f64 ┆     ┆ ons ┆   ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆ --- ┆   ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆ f64 ┆   ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═══╪════════╪═══════╪═══════╪═══════╡
│ cou ┆ 948 ┆ 948 ┆ 948 ┆ … ┆ 94848. ┆ 94848 ┆ 94848 ┆ 94848 │
│ nt  ┆ 48. ┆ 48. ┆ 48. ┆   ┆ 0      ┆ .0    ┆ .0    ┆ .0    │
│     ┆ 0   ┆ 0   ┆ 0   ┆   ┆        ┆       ┆       ┆       │
│ nul ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.0    ┆ 0.0   ┆ 0.0   ┆ 0.0   │
│ l_c ┆     ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ oun ┆     ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ t   ┆     ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ mea ┆ 7.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.0911 ┆ 0.064 ┆ 0.019 ┆ 0.003 │
│ n   ┆ 668 ┆ 440 ┆ 226 ┆   ┆ 77     ┆ 324   ┆ 241   ┆ 574   │
│     ┆ 65  ┆ 71  ┆ 99  ┆   ┆        ┆       ┆       ┆       │
│ std ┆ 41. ┆ 0.3 ┆ 0.1 ┆ … ┆ 0.4489 ┆ 0.346 ┆ 0.157 ┆ 0.062 │
│     ┆ 377 ┆ 146 ┆ 977 ┆   ┆ 56     ┆ 668   ┆ 134   ┆ 271   │
│     ┆ 076 ┆ 75  ┆ 8   ┆   ┆        ┆       ┆       ┆       │
│ min ┆ -7. ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.0    ┆ 0.0   ┆ 0.0   ┆ 0.0   │
│     ┆ 0   ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ 25% ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.0    ┆ 0.0   ┆ 0.0   ┆ 0.0   │
│ 50% ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.0    ┆ 0.0   ┆ 0.0   ┆ 0.0   │
│ 75% ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.0    ┆ 0.0   ┆ 0.0   ┆ 0.0   │
│ max ┆ 525 ┆ 6.0 ┆ 5.0 ┆ … ┆ 8.0    ┆ 7.0   ┆ 4.0   ┆ 3.0   │
│     ┆ .0  ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴───┴────────┴───────┴───────┴───────┘

In [8]:
player_stats.dtypes

[String,
 String,
 String,
 String,
 String,
 String,
 Int32,
 Int32,
 String,
 String,
 String,
 String,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Float64,
 Float64,
 Int32,
 Float64,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Float64,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Float64,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Float64,
 Float64,
 Float64,
 Float64,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Float64,
 Float64,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Float64,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 String,
 String,
 String,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Float64,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Float64,
 Float64]

## Secondary dataset 1: Team stats (`team_stats`)

One row = one team's cumulative stats for the 2025 regular season.
Notable columns: `passing_yards`, `rushing_yards`, `passing_tds`, `rushing_tds`.

In [9]:
# Loads team-level stats for a given season/season-type ("reg" or "post")
team_stats = nfl.load_team_stats(2025, "reg")
team_stats.shape

(32, 136)

In [10]:
team_stats.describe()

shape: (9, 137)
┌─────┬─────┬─────┬─────┬───┬────────┬───────┬───────┬───────┐
│ sta ┆ sea ┆ tea ┆ sea ┆ … ┆ pt_ret ┆ pt_re ┆ pt_re ┆ pt_ne │
│ tis ┆ son ┆ m   ┆ son ┆   ┆ urned  ┆ turn_ ┆ turn_ ┆ t_yar │
│ tic ┆ --- ┆ --- ┆ _ty ┆   ┆ ---    ┆ yards ┆ tds   ┆ ds    │
│ --- ┆ f64 ┆ str ┆ pe  ┆   ┆ f64    ┆ ---   ┆ ---   ┆ ---   │
│ str ┆     ┆     ┆ --- ┆   ┆        ┆ f64   ┆ f64   ┆ f64   │
│     ┆     ┆     ┆ str ┆   ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═══╪════════╪═══════╪═══════╪═══════╡
│ cou ┆ 32. ┆ 32  ┆ 32  ┆ … ┆ 32.0   ┆ 32.0  ┆ 32.0  ┆ 32.0  │
│ nt  ┆ 0   ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ nul ┆ 0.0 ┆ 0   ┆ 0   ┆ … ┆ 0.0    ┆ 0.0   ┆ 0.0   ┆ 0.0   │
│ l_c ┆     ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ oun ┆     ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ t   ┆     ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ mea ┆ 202 ┆ nul ┆ nul ┆ … ┆ 25.843 ┆ 264.1 ┆ 0.468 ┆ 2489. │
│ n   ┆ 5.0 ┆ l   ┆ l   ┆   ┆ 75     ┆ 5625  ┆ 75    ┆ 65625 │
│ std ┆ 0.0 ┆ nul ┆ nul ┆ … ┆ 5.5130 ┆ 91.41 ┆ 0.671 ┆ 438.6 │
│     ┆     ┆ l   ┆ l   ┆   ┆ 89     ┆ 5785  ┆ 271   ┆ 10313 │
│ min ┆ 202 ┆ ARI ┆ REG ┆ … ┆ 16.0   ┆ 114.0 ┆ 0.0   ┆ 1618. │
│     ┆ 5.0 ┆     ┆     ┆   ┆        ┆       ┆       ┆ 0     │
│ 25% ┆ 202 ┆ nul ┆ nul ┆ … ┆ 22.0   ┆ 205.0 ┆ 0.0   ┆ 2179. │
│     ┆ 5.0 ┆ l   ┆ l   ┆   ┆        ┆       ┆       ┆ 0     │
│ 50% ┆ 202 ┆ nul ┆ nul ┆ … ┆ 25.0   ┆ 277.0 ┆ 0.0   ┆ 2486. │
│     ┆ 5.0 ┆ l   ┆ l   ┆   ┆        ┆       ┆       ┆ 0     │
│ 75% ┆ 202 ┆ nul ┆ nul ┆ … ┆ 28.0   ┆ 312.0 ┆ 1.0   ┆ 2788. │
│     ┆ 5.0 ┆ l   ┆ l   ┆   ┆        ┆       ┆       ┆ 0     │
│ max ┆ 202 ┆ WAS ┆ REG ┆ … ┆ 41.0   ┆ 522.0 ┆ 2.0   ┆ 3423. │
│     ┆ 5.0 ┆     ┆     ┆   ┆        ┆       ┆       ┆ 0     │
└─────┴─────┴─────┴─────┴───┴────────┴───────┴───────┴───────┘

## Secondary dataset 2: Next Gen Stats receiving (`wr_receiving`)

NFL Next Gen Stats receiving data, filtered down to 2025 regular-season wide
receiver weekly observations (the dataset also contains non-WR positions and
season-summary rows, so we narrow to what this project needs). Notable
columns: `avg_separation`, `avg_cushion`, `targets`, `receptions`, `yards`,
`avg_yac`. Will be used to investigate how average WR separation relates to
receiving yardage -- that analysis itself belongs in the EDA checkpoint, not here.

In [11]:
ngs_receiving = nfl.load_nextgen_stats(
    seasons=2025,
    stat_type="receiving"
)

ngs_receiving.shape

(1402, 23)

In [12]:
ngs_receiving.columns

['season',
 'season_type',
 'week',
 'player_display_name',
 'player_position',
 'team_abbr',
 'avg_cushion',
 'avg_separation',
 'avg_intended_air_yards',
 'percent_share_of_intended_air_yards',
 'receptions',
 'targets',
 'catch_percentage',
 'yards',
 'rec_touchdowns',
 'avg_yac',
 'avg_expected_yac',
 'avg_yac_above_expectation',
 'player_gsis_id',
 'player_first_name',
 'player_last_name',
 'player_jersey_number',
 'player_short_name']

In [13]:
wr_receiving = (
    ngs_receiving
    .filter(
        (pl.col("season") == 2025) &
        (pl.col("season_type") == "REG") &
        (pl.col("player_position") == "WR") &
        (pl.col("week") > 0)
    )
    .select([
        "player_gsis_id",
        "player_display_name",
        "player_position",
        "team_abbr",
        "season",
        "week",
        "avg_cushion",
        "avg_separation",
        "avg_intended_air_yards",
        "targets",
        "receptions",
        "catch_percentage",
        "yards",
        "rec_touchdowns",
        "avg_yac",
        "avg_expected_yac",
        "avg_yac_above_expectation"
    ])
)

wr_receiving.shape

(888, 17)

In [14]:
wr_receiving.head()

shape: (5, 17)
┌─────┬─────┬─────┬─────┬───┬────────┬───────┬───────┬───────┐
│ pla ┆ pla ┆ pla ┆ tea ┆ … ┆ rec_to ┆ avg_y ┆ avg_e ┆ avg_y │
│ yer ┆ yer ┆ yer ┆ m_a ┆   ┆ uchdow ┆ ac    ┆ xpect ┆ ac_ab │
│ _gs ┆ _di ┆ _po ┆ bbr ┆   ┆ ns     ┆ ---   ┆ ed_ya ┆ ove_e │
│ is_ ┆ spl ┆ sit ┆ --- ┆   ┆ ---    ┆ f64   ┆ c     ┆ xpect │
│ id  ┆ ay_ ┆ ion ┆ str ┆   ┆ i32    ┆       ┆ ---   ┆ ation │
│ --- ┆ nam ┆ --- ┆     ┆   ┆        ┆       ┆ f64   ┆ ---   │
│ str ┆ e   ┆ str ┆     ┆   ┆        ┆       ┆       ┆ f64   │
│     ┆ --- ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│     ┆ str ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═══╪════════╪═══════╪═══════╪═══════╡
│ 00- ┆ Eme ┆ WR  ┆ TB  ┆ … ┆ 2      ┆ 4.302 ┆ 6.822 ┆ -2.52 │
│ 004 ┆ ka  ┆     ┆     ┆   ┆        ┆ 5     ┆ 941   ┆ 0441  │
│ 012 ┆ Egb ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ 9   ┆ uka ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ 00- ┆ Cal ┆ WR  ┆ TEN ┆ … ┆ 0      ┆ 3.25  ┆ 4.041 ┆ -0.79 │
│ 003 ┆ vin ┆     ┆     ┆   ┆        ┆       ┆ 631   ┆ 1631  │
│ 483 ┆ Rid ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ 7   ┆ ley ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ 00- ┆ Jos ┆ WR  ┆ BUF ┆ … ┆ 0      ┆ 2.416 ┆ 2.146 ┆ 0.269 │
│ 003 ┆ h   ┆     ┆     ┆   ┆        ┆       ┆ 43    ┆ 57    │
│ 698 ┆ Pal ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ 8   ┆ mer ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ 00- ┆ Jam ┆ WR  ┆ DET ┆ … ┆ 0      ┆ 2.067 ┆ 1.881 ┆ 0.185 │
│ 003 ┆ eso ┆     ┆     ┆   ┆        ┆ 5     ┆ 923   ┆ 577   │
│ 724 ┆ n   ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ 0   ┆ Wil ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│     ┆ lia ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│     ┆ ms  ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ 00- ┆ Tra ┆ WR  ┆ JAX ┆ … ┆ 0      ┆ 3.951 ┆ 4.426 ┆ -0.47 │
│ 004 ┆ vis ┆     ┆     ┆   ┆        ┆ 667   ┆ 598   ┆ 4931  │
│ 071 ┆ Hun ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ 8   ┆ ter ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴───┴────────┴───────┴───────┴───────┘