# Primary dataset: player weekly stats

Source: [nflverse](https://github.com/nflverse/nflreadpy), accessed via the `nflreadpy` package.

One row = one player's stat line for one week of one season. Includes `rushing_*`
columns (rushing_yards, rushing_tds, rushing_epa, carries, ...) and `passing_*`
columns (passing_yards, passing_tds, passing_epa, attempts, ...) side by side,
so this is the main dataset for comparing rushing vs. passing production
at the player level.

In [1]:
import polars as pl
import nflreadpy as nfl

In [2]:
# Adjust seasons as the group settles on scope.
player_stats = nfl.load_player_stats([2021, 2022, 2023, 2024, 2025])
player_stats.shape

(94848, 150)

In [3]:
player_stats.head()

shape: (5, 150)
┌─────┬─────┬─────┬─────┬───┬────────┬───────┬───────┬───────┐
│ pla ┆ pla ┆ pla ┆ pos ┆ … ┆ pt_ret ┆ pt_ne ┆ fanta ┆ fanta │
│ yer ┆ yer ┆ yer ┆ iti ┆   ┆ urn_td ┆ t_yar ┆ sy_po ┆ sy_po │
│ _id ┆ _na ┆ _di ┆ on  ┆   ┆ s      ┆ ds    ┆ ints  ┆ ints_ │
│ --- ┆ me  ┆ spl ┆ --- ┆   ┆ ---    ┆ ---   ┆ ---   ┆ ppr   │
│ str ┆ --- ┆ ay_ ┆ str ┆   ┆ i32    ┆ i32   ┆ f64   ┆ ---   │
│     ┆ str ┆ nam ┆     ┆   ┆        ┆       ┆       ┆ f64   │
│     ┆     ┆ e   ┆     ┆   ┆        ┆       ┆       ┆       │
│     ┆     ┆ --- ┆     ┆   ┆        ┆       ┆       ┆       │
│     ┆     ┆ str ┆     ┆   ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═══╪════════╪═══════╪═══════╪═══════╡
│ 00- ┆ T.B ┆ Tom ┆ QB  ┆ … ┆ 0      ┆ 0     ┆ 27.16 ┆ 27.16 │
│ 001 ┆ rad ┆ Bra ┆     ┆   ┆        ┆       ┆       ┆       │
│ 959 ┆ y   ┆ dy  ┆     ┆   ┆        ┆       ┆       ┆       │
│ 6   ┆     ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ 00- ┆ A.L ┆ And ┆ P   ┆ … ┆ 0      ┆ 124   ┆ 0.0   ┆ 0.0   │
│ 002 ┆ ee  ┆ y   ┆     ┆   ┆        ┆       ┆       ┆       │
│ 282 ┆     ┆ Lee ┆     ┆   ┆        ┆       ┆       ┆       │
│ 4   ┆     ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ 00- ┆ B.R ┆ Ben ┆ QB  ┆ … ┆ 0      ┆ 0     ┆ 12.02 ┆ 12.02 │
│ 002 ┆ oet ┆ Roe ┆     ┆   ┆        ┆       ┆       ┆       │
│ 292 ┆ hli ┆ thl ┆     ┆   ┆        ┆       ┆       ┆       │
│ 4   ┆ sbe ┆ isb ┆     ┆   ┆        ┆       ┆       ┆       │
│     ┆ rge ┆ erg ┆     ┆   ┆        ┆       ┆       ┆       │
│     ┆ r   ┆ er  ┆     ┆   ┆        ┆       ┆       ┆       │
│ 00- ┆ R.G ┆ Rob ┆ K   ┆ … ┆ 0      ┆ 0     ┆ 0.0   ┆ 0.0   │
│ 002 ┆ oul ┆ bie ┆     ┆   ┆        ┆       ┆       ┆       │
│ 325 ┆ d   ┆ Gou ┆     ┆   ┆        ┆       ┆       ┆       │
│ 2   ┆     ┆ ld  ┆     ┆   ┆        ┆       ┆       ┆       │
│ 00- ┆ Aa. ┆ Aar ┆ QB  ┆ … ┆ 0      ┆ 0     ┆ 1.32  ┆ 1.32  │
│ 002 ┆ Rod ┆ on  ┆     ┆   ┆        ┆       ┆       ┆       │
│ 345 ┆ ger ┆ Rod ┆     ┆   ┆        ┆       ┆       ┆       │
│ 9   ┆ s   ┆ ger ┆     ┆   ┆        ┆       ┆       ┆       │
│     ┆     ┆ s   ┆     ┆   ┆        ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴───┴────────┴───────┴───────┴───────┘

In [4]:
# Columns relevant to rushing vs. passing
cols = [c for c in player_stats.columns if c.startswith('rushing_') or c.startswith('passing_')]
cols

['passing_yards',
 'passing_tds',
 'passing_interceptions',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_cpoe',
 'passing_2pt_conversions',
 'passing_10',
 'passing_16',
 'passing_20',
 'passing_40',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'rushing_10',
 'rushing_12',
 'rushing_20',
 'rushing_40']

In [5]:
player_stats.select(cols).describe()

shape: (9, 25)
┌─────┬─────┬─────┬─────┬───┬────────┬───────┬───────┬───────┐
│ sta ┆ pas ┆ pas ┆ pas ┆ … ┆ rushin ┆ rushi ┆ rushi ┆ rushi │
│ tis ┆ sin ┆ sin ┆ sin ┆   ┆ g_10   ┆ ng_12 ┆ ng_20 ┆ ng_40 │
│ tic ┆ g_y ┆ g_t ┆ g_i ┆   ┆ ---    ┆ ---   ┆ ---   ┆ ---   │
│ --- ┆ ard ┆ ds  ┆ nte ┆   ┆ f64    ┆ f64   ┆ f64   ┆ f64   │
│ str ┆ s   ┆ --- ┆ rce ┆   ┆        ┆       ┆       ┆       │
│     ┆ --- ┆ f64 ┆ pti ┆   ┆        ┆       ┆       ┆       │
│     ┆ f64 ┆     ┆ ons ┆   ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆ --- ┆   ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆ f64 ┆   ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═══╪════════╪═══════╪═══════╪═══════╡
│ cou ┆ 948 ┆ 948 ┆ 948 ┆ … ┆ 94848. ┆ 94848 ┆ 94848 ┆ 94848 │
│ nt  ┆ 48. ┆ 48. ┆ 48. ┆   ┆ 0      ┆ .0    ┆ .0    ┆ .0    │
│     ┆ 0   ┆ 0   ┆ 0   ┆   ┆        ┆       ┆       ┆       │
│ nul ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.0    ┆ 0.0   ┆ 0.0   ┆ 0.0   │
│ l_c ┆     ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ oun ┆     ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ t   ┆     ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ mea ┆ 7.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.0911 ┆ 0.064 ┆ 0.019 ┆ 0.003 │
│ n   ┆ 668 ┆ 440 ┆ 226 ┆   ┆ 77     ┆ 324   ┆ 241   ┆ 574   │
│     ┆ 65  ┆ 71  ┆ 99  ┆   ┆        ┆       ┆       ┆       │
│ std ┆ 41. ┆ 0.3 ┆ 0.1 ┆ … ┆ 0.4489 ┆ 0.346 ┆ 0.157 ┆ 0.062 │
│     ┆ 377 ┆ 146 ┆ 977 ┆   ┆ 56     ┆ 668   ┆ 134   ┆ 271   │
│     ┆ 076 ┆ 75  ┆ 8   ┆   ┆        ┆       ┆       ┆       │
│ min ┆ -7. ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.0    ┆ 0.0   ┆ 0.0   ┆ 0.0   │
│     ┆ 0   ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
│ 25% ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.0    ┆ 0.0   ┆ 0.0   ┆ 0.0   │
│ 50% ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.0    ┆ 0.0   ┆ 0.0   ┆ 0.0   │
│ 75% ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ … ┆ 0.0    ┆ 0.0   ┆ 0.0   ┆ 0.0   │
│ max ┆ 525 ┆ 6.0 ┆ 5.0 ┆ … ┆ 8.0    ┆ 7.0   ┆ 4.0   ┆ 3.0   │
│     ┆ .0  ┆     ┆     ┆   ┆        ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴───┴────────┴───────┴───────┴───────┘

In [6]:
player_stats.dtypes

[String,
 String,
 String,
 String,
 String,
 String,
 Int32,
 Int32,
 String,
 String,
 String,
 String,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Float64,
 Float64,
 Int32,
 Float64,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Float64,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Float64,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Float64,
 Float64,
 Float64,
 Float64,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Float64,
 Float64,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Float64,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 String,
 String,
 String,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Float64,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Int32,
 Float64,
 Float64]